//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipLine.Plugin.Recordings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SipLine.Plugin.Recordings.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PluginName => ResourceManager.GetString("PluginName", resourceCulture);
        public static string PluginDescription => ResourceManager.GetString("PluginDescription", resourceCulture);
        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Subtitle => ResourceManager.GetString("Subtitle", resourceCulture);
        public static string TotalCountFormat => ResourceManager.GetString("TotalCountFormat", resourceCulture);
        public static string OpenFolder => ResourceManager.GetString("OpenFolder", resourceCulture);
        public static string Refresh => ResourceManager.GetString("Refresh", resourceCulture);
        public static string All => ResourceManager.GetString("All", resourceCulture);
        public static string Today => ResourceManager.GetString("Today", resourceCulture);
        public static string ThisWeek => ResourceManager.GetString("ThisWeek", resourceCulture);
        public static string ThisMonth => ResourceManager.GetString("ThisMonth", resourceCulture);
        public static string Loading => ResourceManager.GetString("Loading", resourceCulture);
        public static string NoRecordings => ResourceManager.GetString("NoRecordings", resourceCulture);
        public static string NoRecordingsDesc => ResourceManager.GetString("NoRecordingsDesc", resourceCulture);
        public static string Play => ResourceManager.GetString("Play", resourceCulture);
        public static string Stop => ResourceManager.GetString("Stop", resourceCulture);
        public static string Email => ResourceManager.GetString("Email", resourceCulture);
        public static string Export => ResourceManager.GetString("Export", resourceCulture);
        public static string Delete => ResourceManager.GetString("Delete", resourceCulture);
    }
}
